---
- name: Error Handling
  hosts: all
  become: true
  tasks: 
  - name: Install httpd package
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install http --- package
    yum:
      name: http---
      state: present
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: start httpd package
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
