---
- name: Install https or apache package
  hosts: webservers
  become: yes
  tasks:
  - name: Install Httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: start httpd package
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: Install apache
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debain"

  - name: Start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debain"
