---
- name: Install Multiple Packages
  hosts: webservers
  become: true
  tasks:
  - name: Installing packges
    yum: 
      name: ['git', 'httpd', 'tree', 'mysql', 'gcc', 'vim', 'which']
      state: installed

