---
- name: Install and Start the Service
  hosts: all
  become: true
  tasks:
  - name: Installing Package
    yum:
      name: httpd
      state: present
  - name: Start Service
    service:
      name: httpd
      state: started
