---
- name: setup tomcat
  hosts: all
  become: true
  tasks: 
  - name: install java on RedHat
    yum: 
      name: java
      state: present
    when: ansible_os_family == "RedHat"

  - name: install java on Debain
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: To Download Tomcat
    get_url: 
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.tar.gz
      dest: /opt

  - name: Extract the download file
    unarchive: 
      src: /opt/apache-tomcat-8.5.85.tar.gz
      dest: /opt
      remote_src: true

  - name: Executable permissions
    file:
      path: /opt/apache-tomcat-8.5.85/bin/startup.sh
      mode: 0777

  - name: start tomcat
    shell: nohup ./startup.sh

    args:
      chdir: /opt/apache-tomcat-8.5.85/bin

