---
# tasks file for setup_apache_role
- name: install httpd package
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: start httpd service

- name: install apache2 package
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: copy file
  copy:
    src: /home/saiadmin/playbooks/index.html
    dest: /var/www/html/
    mode: 0666
